name: Build

on: [push, pull_request]

jobs:
  Build-Base:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: ['8', '10', '12', '13']
    runs-on: ${{ matrix.os }}
    name: build and test (${{ matrix.os }}|node-${{ matrix.node }})

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.2.0
        with:
          node-version: ${{ matrix.node }}
      - run: cd base-structure
      - run: node --version
      - run: npm ci
      - run: npm run lint
      - run: npm test

  Build-HK:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: ['13']
    runs-on: ${{ matrix.os }}
    name: build and test (${{ matrix.os }}|node-${{ matrix.node }})

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.2.0
        with:
          node-version: ${{ matrix.node }}
      - run: cd house-keeping
      - run: node --version
      - run: npm ci
      - run: npm run lint
      - run: npm test
